apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: monstericon
  name: monstericon
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monstericon
    spec:
      containers:
      - env:
        - name: CONTEXT
          value: DEV
        image: monstericon
        name: monstericon
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
